// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace WebBiblioteka.Models
{
    public partial class Book
    {
        [Key]
        public int BookId { get; set; }
        [Required(ErrorMessage = "Please enter the name")]
        [StringLength(60, ErrorMessage = "Maximum 60 characters, and minimum 3", MinimumLength = 3)]
        public string Title { get; set; }
        [Required(ErrorMessage = "Please enter the number of pages")]
        public int NumOfPages { get; set; }
        [Display(Name = "Cover")]
        [MaxLength]
        

        //saving image in db, not on server
        public byte[] Picture { get; set; }
        [StringLength(20)]
        public string TypeOfFile { get; set; }
        [Required(ErrorMessage = "Please enter the author")]
        public string Author { get; set; }
        [StringLength(200, ErrorMessage = "Minimum 5 and maximum 200 characters", MinimumLength = 5)]
        [Required(ErrorMessage = "Please enter the description")]
        [DataType(DataType.MultilineText)]
        public string BookDesc { get; set; }
        public bool IsApproved { get; set; }
    }
}